### ISSUE TITLE
Version update alert.

### ISSUE THREAD

**Issue by carloslozano** [AdaptiveMe/adaptive-cloud-cli#13]
Show the user that a new version is available.

Two types:

**Recommended** update - we _recommend_ the update: you can still use your existing CLI.
**Mandatory** update - you must update before continuing to use the CLI.

**Comment by ferranvila** [comment]
https://github.com/AdaptiveMe/adaptive-cloud-cli/commit/3da742b28c6f02f8181fd7b7c8cf98be9006ec29
